version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-intern
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 286202
      POSTGRES_DB: webdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"    
    depends_on:
      - db
volumes:
  postgres-data: