version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-intern
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
